name: Node.js lint
on:
  workflow_call:
jobs:
  lint_typecheck:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache node_modules
        id: node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            example/node_modules
            .yarn/cache
          key: node-modules
      - run: yarn
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn pack --out '%s_%v.tgz'
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: '${{ github.workspace }}/*.tgz'
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '${{ github.workspace }}/*.tgz'
