name: semantic
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
permissions:
  pull-requests: read
jobs:
  semantic-pr:
    name: semantic-pr
    uses: evva-sfw/.github/semantic.yml@main
